version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgre2024
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  springboot:
    build:
      context: ./prueba-tecnica-equifax
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/mi_basedatos
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pgre2024
    networks:
      - backend

  angular:
    build:
      context: ./prueba-tecnica-equifax-front
      dockerfile: Dockerfile
    depends_on:
      - springboot
    ports:
      - "80:80"
    networks:
      - backend
      - frontend

networks:
  backend:
  frontend:

volumes:
  postgres-data:
